apiVersion: console.openshift.io/v1alpha1
kind: ConsolePlugin
metadata:
  name: {{ include "console-plugin-nvidia-gpu.fullname" . }}
  labels:
    {{- include "console-plugin-nvidia-gpu.labels" . | nindent 4 }}
spec:
  displayName: 'Console Plugin NVIDIA GPU Template'
  service:
    name: {{ include "console-plugin-nvidia-gpu.fullname" . }}
    namespace: {{ .Release.Namespace }}
    port: 9443
    basePath: '/'
