apiVersion: v1
kind: Service
metadata:
  name: {{ include "console-plugin-nvidia-gpu.fullname" . }}
  labels:
    {{- include "console-plugin-nvidia-gpu.labels" . | nindent 4 }}
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: plugin-serving-cert
spec:
  ports:
  - name: 9443-tcp
    protocol: TCP
    port: 9443
    targetPort: 9443
  selector:
    {{- include "console-plugin-nvidia-gpu.selectorLabels" . | nindent 4 }}
  type: ClusterIP
  sessionAffinity: None
